/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import ModeloBeans.BeansLogin;
import ModeloConection.ConexaoBD;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author vinic
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    private Connection conexao = null;
    public TelaLogin() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(CadastroFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        try {
            conexao = ConexaoBD.getConexao();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERRO Ao Estabelecer Conexão!\nErro: " + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Entrar = new javax.swing.JButton();
        Senha = new javax.swing.JPasswordField();
        Sair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Login = new javax.swing.JTextField();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("95's Club");
        getContentPane().setLayout(null);

        Entrar.setText("Entrar");
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });
        getContentPane().add(Entrar);
        Entrar.setBounds(540, 220, 70, 23);

        Senha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaActionPerformed(evt);
            }
        });
        Senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SenhaKeyPressed(evt);
            }
        });
        getContentPane().add(Senha);
        Senha.setBounds(540, 190, 150, 20);

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        getContentPane().add(Sair);
        Sair.setBounds(620, 220, 70, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 160, 40, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Senha:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(480, 190, 43, 17);
        getContentPane().add(Login);
        Login.setBounds(540, 160, 150, 20);

        fundo.setBackground(new java.awt.Color(0, 0, 0));
        fundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundo Tela Login.png"))); // NOI18N
        fundo.setText("jLabel1");
        getContentPane().add(fundo);
        fundo.setBounds(0, -20, 770, 470);

        setSize(new java.awt.Dimension(770, 465));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void SenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SenhaKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try {
                String login = Login.getText();
                String senha = Senha.getText();
                String func = consultaFunc(login, senha);
                boolean resposta = consultar(login, senha);
                consultaCredito(login);
                BeansLogin log = new BeansLogin();
                if (resposta == true){
                    log.setLogin(login);
                    JOptionPane.showMessageDialog(rootPane, "login realizado com sucesso!");
                    switch (func) {
                        case "Funcionário":
                        {
                            TelaPrincipal2 tela = new TelaPrincipal2();
                            tela.setVisible(true);
                            dispose();
                            break;
                        }
                        case "Gerente":
                        {
                            TelaPrincipal1 tela = new TelaPrincipal1();
                            tela.setVisible(true);
                            dispose();
                            break;
                        }
                        default:
                        {
                            TelaPrincipal3 tela = new TelaPrincipal3();
                            tela.setVisible(true);
                            dispose();
                            break;
                        }
                    }
                    
                }else {
                    JOptionPane.showMessageDialog(rootPane, "login não realizado!\n Favor conferir o usuario e senha digitado!");
                }   } catch (SQLException ex) {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    }//GEN-LAST:event_SenhaKeyPressed

    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
        String login = Login.getText();
        String senha = Senha.getText();
        String func = consultaFunc(login, senha);
        boolean resposta = consultar(login, senha);
        try {
            consultaCredito(login);
        } catch (SQLException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (resposta == true){
            BeansLogin log = new BeansLogin();
            log.setLogin(login);
            JOptionPane.showMessageDialog(rootPane, "login realizado com sucesso!");
            switch (func) {
                case "Funcionário":
                    {
                        TelaPrincipal2 tela = new TelaPrincipal2();
                        tela.setVisible(true);
                        dispose();
                        break;
                    }
                case "Gerente":
                    {
                        TelaPrincipal1 tela = new TelaPrincipal1();
                        tela.setVisible(true);
                        dispose();
                        break;
                    }
                default:
                    {
                        TelaPrincipal3 tela = new TelaPrincipal3();
                        tela.setVisible(true);
                        dispose();
                        break;
                    }
            }

        }else {
            JOptionPane.showMessageDialog(rootPane, "login não realizado!\n Favor conferir o usuario e senha digitado!");
        }
    

    }//GEN-LAST:event_EntrarActionPerformed

    public String consultaFunc(String login, String senha){
        try{
            String sql;
            sql = "select funcao from usuario where login = ? and senha = ?";
            PreparedStatement ps;
            String resposta = null;
            ps = conexao.prepareStatement(sql);
            ps.setString(1, login);
            ps.setString(2, senha);
 
            ResultSet rs;
            rs = ps.executeQuery();
            if(rs.next()){
                resposta = rs.getString("funcao");
            }
            
            return resposta;
            
            
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "ERRO Ao Recuperar Função!\nErro: " + ex);
            throw new RuntimeException();
        }
        
    }
    public void consultaCredito(String login) throws SQLException{
            BeansLogin l = new BeansLogin();
            String sql;
            sql = "select credito from cliente where login=?";
            PreparedStatement ps;
            String resposta = null;
            ps = conexao.prepareStatement(sql);
            ps.setString(1, login);

 
            ResultSet rs;
            rs = ps.executeQuery();
            if(rs.next()){
               l.setCredito(rs.getFloat("credito"));
            }
        
    }
 
     public boolean consultar (String login, String senha){
// Manda como parametro para ele duas variaveis para ele procurar no banco de dados!
        try{
            boolean autentificado = false;
            String sql;
            sql = "select login, senha, funcao,nome, id from usuario where login = ? and senha = ?";
            PreparedStatement ps;
            BeansLogin l = new BeansLogin();
            ps = conexao.prepareStatement(sql);
            ps.setString(1, login);
            ps.setString(2, senha);
 
            ResultSet rs;
            rs = ps.executeQuery();
 
            if (rs.next()) {
                rs.getString("login");
                rs.getString("senha");
                rs.getString("funcao");
                l.setNome(rs.getString("nome"));
                BeansLogin.setId(rs.getInt("id"));
                autentificado = true;
            }
 
            ps.close();
   
 
            return autentificado;
 
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERRO Ao Recuperar Loguin ou Senha!\nErro: " + ex);
            throw new RuntimeException();
        }
}
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Entrar;
    private javax.swing.JTextField Login;
    private javax.swing.JButton Sair;
    private javax.swing.JPasswordField Senha;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
