/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import ModeloConection.ConexaoBD;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
//import net.sf.jasperreports.engine.JRException;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author vinic
 */
public class TelaPrincipal1 extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal1
     */
    public TelaPrincipal1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Acessos = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        Ingressos = new javax.swing.JRadioButtonMenuItem();
        Funcionarios = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Bebidas = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();
        bebidas = new javax.swing.JRadioButtonMenuItem();
        Clientes = new javax.swing.JRadioButtonMenuItem();
        Funcionario = new javax.swing.JRadioButtonMenuItem();
        Ingredientes = new javax.swing.JRadioButtonMenuItem();
        petiscos = new javax.swing.JRadioButtonMenuItem();
        Recarga = new javax.swing.JRadioButtonMenuItem();
        users = new javax.swing.JRadioButtonMenuItem();
        venda_beb = new javax.swing.JRadioButtonMenuItem();
        venda_ing = new javax.swing.JRadioButtonMenuItem();
        venda_pet = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Sair = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fundo Tela Gerente.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 760, 410);

        jMenu1.setText("Cadastrar");

        Acessos.setSelected(true);
        Acessos.setText("Acessos");
        Acessos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcessosActionPerformed(evt);
            }
        });
        jMenu1.add(Acessos);

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Ingredientes");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem2);

        Ingressos.setSelected(true);
        Ingressos.setText("Ingressos");
        Ingressos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngressosActionPerformed(evt);
            }
        });
        jMenu1.add(Ingressos);

        Funcionarios.setSelected(true);
        Funcionarios.setText("Funcionários");
        Funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncionariosActionPerformed(evt);
            }
        });
        jMenu1.add(Funcionarios);

        jMenu3.setText("Produtos");

        Bebidas.setSelected(true);
        Bebidas.setText("Bebidas");
        Bebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BebidasActionPerformed(evt);
            }
        });
        jMenu3.add(Bebidas);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Petiscos");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItem1);

        jMenu1.add(jMenu3);
        jMenu1.add(jSeparator1);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Relatório");

        bebidas.setSelected(true);
        bebidas.setText("Bebidas");
        bebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bebidasActionPerformed(evt);
            }
        });
        jMenu4.add(bebidas);

        Clientes.setSelected(true);
        Clientes.setText("Clientes");
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });
        jMenu4.add(Clientes);

        Funcionario.setSelected(true);
        Funcionario.setText("Funcionários");
        Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncionarioActionPerformed(evt);
            }
        });
        jMenu4.add(Funcionario);

        Ingredientes.setSelected(true);
        Ingredientes.setText("Ingredientes");
        Ingredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngredientesActionPerformed(evt);
            }
        });
        jMenu4.add(Ingredientes);

        petiscos.setSelected(true);
        petiscos.setText("Petiscos");
        petiscos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petiscosActionPerformed(evt);
            }
        });
        jMenu4.add(petiscos);

        Recarga.setSelected(true);
        Recarga.setText("Recargas");
        Recarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecargaActionPerformed(evt);
            }
        });
        jMenu4.add(Recarga);

        users.setSelected(true);
        users.setText("Usuários");
        users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersActionPerformed(evt);
            }
        });
        jMenu4.add(users);

        venda_beb.setSelected(true);
        venda_beb.setText("Venda de Bebidas");
        venda_beb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venda_bebActionPerformed(evt);
            }
        });
        jMenu4.add(venda_beb);

        venda_ing.setSelected(true);
        venda_ing.setText("Venda de Ingressos");
        venda_ing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venda_ingActionPerformed(evt);
            }
        });
        jMenu4.add(venda_ing);

        venda_pet.setSelected(true);
        venda_pet.setText("Venda de Petiscos");
        venda_pet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venda_petActionPerformed(evt);
            }
        });
        jMenu4.add(venda_pet);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Alternar Tela");

        Sair.setSelected(true);
        Sair.setText("Tela de Login");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        jMenu2.add(Sair);

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("Tela de Funcionário");
        jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(774, 467));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        TelaLogin tela = new TelaLogin();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void FuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncionariosActionPerformed
        CadastroFuncionario tela = new CadastroFuncionario();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_FuncionariosActionPerformed

    private void AcessosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcessosActionPerformed
        Acessos tela = new Acessos();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_AcessosActionPerformed

    private void BebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BebidasActionPerformed
       CadastroBebidas tela = new CadastroBebidas();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_BebidasActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        CadastroPetiscos tela = new CadastroPetiscos();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        CadastroIngredientes tela = new CadastroIngredientes();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void jRadioButtonMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem3ActionPerformed
        TelaPrincipal2 tela = new TelaPrincipal2();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jRadioButtonMenuItem3ActionPerformed

    private void IngressosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngressosActionPerformed
        CadastroIngressos tela = new CadastroIngressos();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_IngressosActionPerformed

    private void venda_petActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venda_petActionPerformed
        Connection conn = null;
        try {
            conn = ConexaoBD.getConexao();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
        }
        //JasperPrint jasperprint = null;
        //ALTERAR CAMINHO DEPENDENDO DO PC//
      /*  String src = "C:\\Users\\vinic\\JaspersoftWorkspace\\MyReports\\vendapetiscos.jasper";
        try {
            jasperprint = JasperFillManager.fillReport(src, null, conn);
        } catch (JRException ex) {
            System.out.println("ERRO: "+ex);
        }
        JasperViewer view = new JasperViewer(jasperprint, false);*/
       // view.setVisible(true);
    }//GEN-LAST:event_venda_petActionPerformed

    private void venda_ingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venda_ingActionPerformed
        Connection conn = null;
        try {
            conn = ConexaoBD.getConexao();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
        }
       /* JasperPrint jasperprint = null;
        //ALTERAR CAMINHO DEPENDENDO DO PC//
        String src = "C:\\Users\\vinic\\JaspersoftWorkspace\\MyReports\\vendaingresso.jasper";
        try {
            jasperprint = JasperFillManager.fillReport(src, null, conn);
        } catch (JRException ex) {
            System.out.println("ERRO: "+ex);
        }
        JasperViewer view = new JasperViewer(jasperprint, false);
        view.setVisible(true);*/
    }//GEN-LAST:event_venda_ingActionPerformed

    private void venda_bebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venda_bebActionPerformed
        Connection conn = null;
        try {
            conn = ConexaoBD.getConexao();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
        }
       /* JasperPrint jasperprint = null;
        //ALTERAR CAMINHO DEPENDENDO DO PC//
        String src = "C:\\Users\\vinic\\JaspersoftWorkspace\\MyReports\\vendabebidas.jasper";
        try {
            jasperprint = JasperFillManager.fillReport(src, null, conn);
        } catch (JRException ex) {
            System.out.println("ERRO: "+ex);
        }
        JasperViewer view = new JasperViewer(jasperprint, false);
        view.setVisible(true);*/
    }//GEN-LAST:event_venda_bebActionPerformed

    private void usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersActionPerformed
        Connection conn = null;
        try {
            conn = ConexaoBD.getConexao();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*JasperPrint jasperprint = null;
        //ALTERAR CAMINHO DEPENDENDO DO PC//
        String src = "C:\\Users\\vinic\\JaspersoftWorkspace\\MyReports\\Usuario.jasper";
        try {
            jasperprint = JasperFillManager.fillReport(src, null, conn);
        } catch (JRException ex) {
            System.out.println("ERRO: "+ex);
        }
        JasperViewer view = new JasperViewer(jasperprint, false);
        view.setVisible(true);*/
    }//GEN-LAST:event_usersActionPerformed

    private void RecargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecargaActionPerformed
        Connection conn = null;
        try {
            conn = ConexaoBD.getConexao();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*JasperPrint jasperprint = null;
        //ALTERAR CAMINHO DEPENDENDO DO PC//
        String src = "C:\\Users\\vinic\\JaspersoftWorkspace\\MyReports\\recargacredito.jasper";
        try {
            jasperprint = JasperFillManager.fillReport(src, null, conn);
        } catch (JRException ex) {
            System.out.println("ERRO: "+ex);
        }
        JasperViewer view = new JasperViewer(jasperprint, false);
        view.setVisible(true);*/
    }//GEN-LAST:event_RecargaActionPerformed

    private void petiscosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petiscosActionPerformed
        Connection conn = null;
        try {
            conn = ConexaoBD.getConexao();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
        }
       /* JasperPrint jasperprint = null;
        //ALTERAR CAMINHO DEPENDENDO DO PC//
        String src = "C:\\Users\\vinic\\JaspersoftWorkspace\\MyReports\\petiscos.jasper";
        try {
            jasperprint = JasperFillManager.fillReport(src, null, conn);
        } catch (JRException ex) {
            System.out.println("ERRO: "+ex);
        }
        JasperViewer view = new JasperViewer(jasperprint, false);
        view.setVisible(true);*/
    }//GEN-LAST:event_petiscosActionPerformed

    private void IngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngredientesActionPerformed
        Connection conn = null;
        try {
            conn = ConexaoBD.getConexao();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*JasperPrint jasperprint = null;
        //ALTERAR CAMINHO DEPENDENDO DO PC//
        String src = "C:\\Users\\vinic\\JaspersoftWorkspace\\MyReports\\Ingedientes.jasper";
        try {
            jasperprint = JasperFillManager.fillReport(src, null, conn);
        } catch (JRException ex) {
            System.out.println("ERRO: "+ex);
        }
        JasperViewer view = new JasperViewer(jasperprint, false);
        view.setVisible(true);*/
    }//GEN-LAST:event_IngredientesActionPerformed

    private void FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncionarioActionPerformed
        Connection conn = null;
        try {
            conn = ConexaoBD.getConexao();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*JasperPrint jasperprint = null;
        //ALTERAR CAMINHO DEPENDENDO DO PC//
        String src = "C:\\Users\\vinic\\JaspersoftWorkspace\\MyReports\\Funcionario.jasper";
        try {
            jasperprint = JasperFillManager.fillReport(src, null, conn);
        } catch (JRException ex) {
            System.out.println("ERRO: "+ex);
        }
        JasperViewer view = new JasperViewer(jasperprint, false);
        view.setVisible(true);*/
    }//GEN-LAST:event_FuncionarioActionPerformed

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
        Connection conn = null;
        try {
            conn = ConexaoBD.getConexao();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*JasperPrint jasperprint = null;
        //ALTERAR CAMINHO DEPENDENDO DO PC//
        String src = "C:\\Users\\vinic\\JaspersoftWorkspace\\MyReports\\Cliente.jasper";
        try {
            jasperprint = JasperFillManager.fillReport(src, null, conn);
        } catch (JRException ex) {
            System.out.println("ERRO: "+ex);
        }
        JasperViewer view = new JasperViewer(jasperprint, false);
        view.setVisible(true);*/
    }//GEN-LAST:event_ClientesActionPerformed

    private void bebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bebidasActionPerformed
        Connection conn = null;
        try {
            conn = ConexaoBD.getConexao();
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
        }
       /* JasperPrint jasperprint = null;
        //ALTERAR CAMINHO DEPENDENDO DO PC//
        String src = "C:\\Users\\vinic\\JaspersoftWorkspace\\MyReports\\bebidas.jasper";
        try {
            jasperprint = JasperFillManager.fillReport(src, null, conn);
        } catch (JRException ex) {
            System.out.println("ERRO: "+ex);
        }
        JasperViewer view = new JasperViewer(jasperprint, false);
        view.setVisible(true);*/
    }//GEN-LAST:event_bebidasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem Acessos;
    private javax.swing.JRadioButtonMenuItem Bebidas;
    private javax.swing.JRadioButtonMenuItem Clientes;
    private javax.swing.JRadioButtonMenuItem Funcionario;
    private javax.swing.JRadioButtonMenuItem Funcionarios;
    private javax.swing.JRadioButtonMenuItem Ingredientes;
    private javax.swing.JRadioButtonMenuItem Ingressos;
    private javax.swing.JRadioButtonMenuItem Recarga;
    private javax.swing.JRadioButtonMenuItem Sair;
    private javax.swing.JRadioButtonMenuItem bebidas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JRadioButtonMenuItem petiscos;
    private javax.swing.JRadioButtonMenuItem users;
    private javax.swing.JRadioButtonMenuItem venda_beb;
    private javax.swing.JRadioButtonMenuItem venda_ing;
    private javax.swing.JRadioButtonMenuItem venda_pet;
    // End of variables declaration//GEN-END:variables
}
