/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import ModeloBeans.BeansLogin;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author vinic
 */
public class TelaPrincipal3 extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal3
     */
    public TelaPrincipal3() {
         try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(CadastroFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        BeansLogin l = new BeansLogin();
        cpf.setText("Bem Vindo, "+l.getNome());
        String credito = "" + l.getCredito();
        saldoMostrar.setText(credito);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cpf = new javax.swing.JTextField();
        Bebidas = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        Petiscos = new javax.swing.JButton();
        saldoMostrar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 758, 428));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        cpf.setEditable(false);
        cpf.setBackground(new java.awt.Color(0, 0, 0));
        cpf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cpf.setForeground(new java.awt.Color(255, 255, 255));
        cpf.setBorder(null);
        cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfActionPerformed(evt);
            }
        });
        getContentPane().add(cpf);
        cpf.setBounds(0, 0, 280, 30);

        Bebidas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Bebidas.setText("Bebidas");
        Bebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BebidasActionPerformed(evt);
            }
        });
        getContentPane().add(Bebidas);
        Bebidas.setBounds(130, 159, 120, 111);

        Sair.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        getContentPane().add(Sair);
        Sair.setBounds(510, 160, 120, 110);

        Petiscos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Petiscos.setText("Petiscos");
        Petiscos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetiscosActionPerformed(evt);
            }
        });
        getContentPane().add(Petiscos);
        Petiscos.setBounds(320, 160, 120, 110);

        saldoMostrar.setBackground(new java.awt.Color(0, 0, 0));
        saldoMostrar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        saldoMostrar.setForeground(new java.awt.Color(255, 255, 255));
        saldoMostrar.setBorder(null);
        getContentPane().add(saldoMostrar);
        saldoMostrar.setBounds(619, 380, 140, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Saldo:");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(550, 390, 60, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Escolha de fundo[2943].png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setInheritsPopupMenu(false);
        jLabel1.setName(""); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 758, 428);

        setSize(new java.awt.Dimension(774, 467));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        TelaLogin tela = new TelaLogin();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void BebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BebidasActionPerformed
        CompraBebidas tela = new CompraBebidas();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_BebidasActionPerformed

    private void PetiscosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetiscosActionPerformed
        CompraPetiscos tela = new CompraPetiscos();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_PetiscosActionPerformed

    private void cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bebidas;
    private javax.swing.JButton Petiscos;
    private javax.swing.JButton Sair;
    private javax.swing.JTextField cpf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField saldoMostrar;
    // End of variables declaration//GEN-END:variables
}
